---
title: "VMS R Demo"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r, eval = FALSE}
# ------------------------------------------------------------------------------
# data preparation
library(tidyverse)
library(mar)
library(lubridate)
con <- connect_mar()
VID <-
  afli_stofn(con) %>% 
  filter(ar %in% 2014:2017,
         veidarf == 6) %>% 
  collect(n = Inf) %>% 
  pull(skipnr) %>% 
  unique()
VID <- as.character(VID)


VMS <-
    tbl_mar(con, "stk.stk_vms_v") %>% 
    mutate(year = to_number(to_char(posdate, 'YYYY')),
           lon = poslon * 45 / atan(1),
           lat = poslat * 45 / atan(1),
           heading = heading * 45 / atan(1),
           speed = speed * 1.852) %>%
    filter(year %in% c(2014:2017),
           between(lon, -27, -21),
           between(lat, 65.5, 67.25),
           skip_nr %in% VID) %>%
    select(year, mobileid, vid = skip_nr, date = posdate, lon, lat, speed, heading, in_out_of_harbor, harborid) %>%
    collect(n = Inf)
vms <- read_rds("data2/vms.rda")
library(gisland)
attach("/net/hafkaldi/export/home/haf/einarhj/prj2/vms2/data/shapes.rda")
harbours <- fortify(harbours.sp)
x <- data_frame(group = unique(harbours$group)) %>% 
  mutate(id = 1:n())
harbours <- left_join(harbours %>% select(-id), x)
x2 <- df_2_spdf(as.data.frame(harbours), col.names = c("long", "lat", "group", "id"))
vms <-
  vms %>% 
  mutate(p.harbour = gisland::geo_inside(lon, lat, x2, "ID"),
         vid = as.integer(vid),
         year = month(date))
write_rds(vms, path = "data2/vms.rda")
```


```{r global, include=FALSE}
library(tidyverse)
library(lubridate)
library(viridis)
library(leaflet)
library(raster)
vms <-
  read_rds("data2/vms.rda") %>% 
  filter(speed <= 15,
         is.na(p.harbour))

speed <-
  vms %>%  
  mutate(speed = as.integer(round(speed))) %>% 
  group_by(speed) %>% 
  count()

grade <- function(x, dx) {
  brks <- seq(floor(min(x)), ceiling(max(x)),dx)
  ints <- findInterval(x, brks, all.inside = TRUE)
  x <- (brks[ints] + brks[ints + 1]) / 2
  return(x)
}
```

Sidebar {.sidebar data-width=175}
=====================================

```{r}
sidebarPanel(sliderInput(inputId = "Range",
                         label = "Select Range",
                         min = 0, 
                         max = 15, 
                         step = 1,
                         value = c(2, 14)),
             width = 30)
numericInput(inputId = "Grade", label = "Grade", value = 0.1, min = 0.01, max = 0.5, step = 0.01,
  width = NULL)
#selectInput(inputId = "Grade", label = "Grade:",
#            choices = seq(0.01, 0.1, by = 0.01), selected = 0.10)
```



Panel 1
=====================================  

Column 
-------------------------------------

### Speed histogram

```{r}
renderPlot({
  speed %>% 
    mutate(ok = if_else(speed >= min(input$Range) & speed <= max(input$Range), TRUE, FALSE)) %>% 
    ggplot(aes(speed, n, fill = ok)) +
    geom_col() +
    scale_fill_brewer(palette = "Set1")
})
```

### Grid

```{r}
renderPlot({
  vms %>% 
    filter(speed >= min(input$Range) & speed <= max(input$Range)) %>% 
    mutate(lon = grade(lon, dx = input$Grade),
           lat = grade(lat, dx = input$Grade/2)) %>% 
    group_by(lon, lat) %>% 
    summarise(no.pings = n()) %>% 
    ungroup() %>% 
    ggplot() +
    theme_bw() +
    geom_raster(aes(lon, lat, fill = no.pings)) +
    geom_polygon(data = geo::island, aes(lon, lat), fill = "grey") +
    scale_fill_viridis(option = "B", trans = "reverse") +
    coord_quickmap(xlim = range(vms$lon), ylim = range(vms$lat))
})
```

Column 
-------------------------------------

### Effort

```{r}
renderPlot({
  vms %>% 
    filter(speed >= min(input$Range) & speed <= max(input$Range)) %>% 
    mutate(lon = grade(lon, dx = input$Grade),
           lat = grade(lat, dx = input$Grade/2)) %>% 
    group_by(year) %>% 
    summarise(effort = n()) %>% 
    ggplot(aes(year, effort)) +
    geom_point() +
    geom_line() +
    expand_limits(y = 0)
})
```

### Number of distinct vessels

```{r}
renderPlot({
  vms %>% 
    filter(speed >= min(input$Range) & speed <= max(input$Range)) %>% 
    group_by(year) %>% 
    summarise(vid = n_distinct(vid)) %>% 
    ggplot(aes(year, vid)) +
    geom_point() +
    geom_line() +
    expand_limits(y = 0)
})
```

Panel 2
===================================== 

### Some stuff

```{r}
renderLeaflet({
  vmsr <- 
    vms %>% 
    filter(speed >= min(input$Range) & speed <= max(input$Range)) %>% 
    mutate(lon = grade(lon, dx = input$Grade),
           lat = grade(lat, dx = input$Grade/2)) %>% 
    group_by(lon, lat) %>% 
    summarise(no.pings = n()) %>% 
    ungroup() %>% 
    rasterFromXYZ() 
  crs(vmsr) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
  inf <- inferno(12, alpha = 1, begin = 0, end = 1, direction = -1)
  #pal <- colorNumeric(c("#0C2C84", "#41B6C4", "#FFFFCC"), values(vmsr), na.color = "transparent")
  pal <- colorNumeric(inf, values(vmsr), na.color = "transparent")
  leaflet() %>% 
    addTiles() %>%
    addRasterImage(vmsr, colors = pal, opacity = 0.8) %>% 
    addLegend(pal = pal, values = values(vmsr),
    title = "Number of pings")
})
```